components.json, src/components/button.vue
=> fix msgbox component name. fixed #57

package.json, src/index.js
=> fix component name, #74

Makefile, package.json, packages/checklist/src/checklist.vue, packages/field/src/field.vue, packages/radio/src/radio.vue, packages/search/src/search.vue, packages/spinner/components.json, packages/spinner/cooking.conf.js
make 命令使用说明
make install		---  安装依赖
make dev		---  开发模式
make dist		---  编译项目，生成目标文件
make dist-all	---  分别编译每个组件项目
make deploy		---  部署 demo
make pub		---  发布到 npm 上
make pub-all		---  发布各组件到 npm 上
=> add makefile & fix path bug

Makefile, README.md, cooking.demo.js, example/index.tpl, package.json, packages/search/src/search.vue
- update readme
- update build config
=> fix search style, fixed #56

components.json, example/index.tpl, example/nav.config.json, example/pages/index-list.vue, example/route.js, packages/index-list/README.md, packages/index-list/cooking.conf.js, packages/index-list/index.js, packages/index-list/package.json, packages/index-list/src/index-list.vue, packages/index-section/README.md, packages/index-section/cooking.conf.js, packages/index-section/index.js, packages/index-section/package.json, packages/index-section/src/index-section.vue, src/index.js
=> add index list

example/pages/tab-container.vue, example/pages/tabbar.vue, package.json, packages/picker/src/picker-slot.vue, packages/tab-container-item/src/tab-container-item.vue, packages/tab-container/src/tab-container.vue
=> Update TabContainer. close #55

scripts/cooking.component.js
=> Update cooking config

packages/index-list/src/index-list.vue
=> fix an index-list async bug

package.json
=> Lazyload: fix bug in Safari

packages/actionsheet/README.md, packages/indicator/README.md, packages/loadmore/README.md, packages/picker/README.md, packages/popup/README.md
=> update package README

packages/datetime-picker/src/datetime-picker.vue
=> Allow 'YYYY-MM-DD HH:mm:ss' as default value of datetime-picker

packages/index-list/src/index-list.vue, packages/index-section/src/index-section.vue
=> fix indexList style

packages/radio/src/radio.vue
=> simple transition animation on radio

packages/loadmore/src/loadmore.vue
为loadmore添加最大拉动距离，不然可以无限拉好奇怪啊。
//lgtm什么意思？
=> add max pull distance

packages/datetime-picker/src/datetime-picker.vue, packages/picker/src/translate.js
=> fix datetime-picker error

build/release.sh, package.json
=> Fix release

build/bin/build-entry.js, build/release.sh, example/pages/infinite-scroll.vue, package.json, packages/button/cooking.conf.js, packages/cell/cooking.conf.js, packages/checklist/cooking.conf.js, packages/datetime-picker/cooking.conf.js, packages/field/cooking.conf.js, packages/indicator/cooking.conf.js, packages/infinite-scroll/src/directive.js, packages/infinite-scroll/src/infinite-scroll.js, packages/lazyload/src/lazyload.js, packages/picker/src/picker-slot.vue, packages/radio/cooking.conf.js, packages/search/cooking.conf.js, packages/spinner/cooking.conf.js, src/index.js
=> (next)Update infinite-scroll && fix lint

package.json, packages/picker/src/picker-slot.vue, packages/tab-container/src/tab-container.vue
=> (2.0)TabContainer: fix findIndex is undefined in X5 browser, fixed #290

package.json, packages/picker/src/picker-slot.vue, packages/tab-container/src/tab-container.vue
=> TabContainer: fix findIndex is undefined in X5 browser, fixed #290

packages/cell/src/cell.vue, packages/header/src/header.vue
=> Fix Cell style, fixed #285

packages/cell/src/cell.vue, packages/header/src/header.vue
=> (1.x) Fix Cell style, #fixed #285

README.md
=> readme: Fix contributing link

.babelrc
=> babelrc: remove loose mode, fixed #289

packages/field/src/field.vue
=> Field: fix dynamic type

packages/swipe/src/swipe.vue
=> add height:100% on swipe

package.json
=> (1.x)add height: 100% on swipe

packages/picker/src/picker-slot.vue
=> add vendor-prefix on picker's flex

packages/index-list/src/index-list.vue
=> fix index-list async issue

packages/spinner/src/spinner/fading-circle.vue
=> Spinner: fix closed div tag, fixed #315

packages/field/src/field.vue
=> Field: fix build error, fixed #318

packages/cell/src/cell.vue
=> Cell: fix 'is-link' style, fixed #305

packages/cell/src/cell.vue, packages/field/src/field.vue, packages/spinner/src/spinner/fading-circle.vue
=> Sync fixes in master

packages/field/src/field.vue
=> Field: disable clear in readonly state, fixed #304

packages/switch/src/switch.vue
=> Fix switch style in Safari 10, fixed #307

packages/loadmore/src/loadmore.vue
=> Loadmore: add maxDistance

packages/message-box/src/message-box.vue
=> MessageBox: add inputType

packages/tab-container/src/tab-container.vue
=> (1.x)TabContainer: fix exception during route switchover, fixed #320

packages/datetime-picker/src/datetime-picker.vue
=> DatetimePicker: refactor

packages/datetime-picker/src/datetime-picker.vue
=> (1.x)DatetimePicker: refactor

packages/datetime-picker/src/datetime-picker.vue
=> (1.x)DatetimePicker: support 'YYYY-MM-DD HH:mm:ss' as default value

packages/datetime-picker/src/datetime-picker.vue
=> DatetimePicker: support 'YYYY-MM-DD HH:mm:ss' as default value

package.json, packages/actionsheet/src/actionsheet.vue, packages/popup/src/popup.vue
=> ActionSheet/Popup: fix initial appearance issue

package.json, packages/actionsheet/src/actionsheet.vue, packages/popup/src/popup.vue
=> (1.x)ActionSheet/Popup: fix initial appearance issue

packages/checklist/src/checklist.vue, packages/radio/src/radio.vue, packages/switch/src/switch.vue
=> Switch/Checklist/Radio: fix style bug in UC

package.json, packages/checklist/src/checklist.vue, packages/radio/src/radio.vue, packages/switch/src/switch.vue
=> (1.x)Switch/Checklist/Radio: fix style bug in UC

components.json, example/nav.config.json, example/pages/palette-button.vue, packages/palette-button/README.md, packages/palette-button/cooking.conf.js, packages/palette-button/index.js, packages/palette-button/package.json, packages/palette-button/src/palette-button.vue, src/index.js
this is a set of buttons that has a cool animation
=> add Palette Button component

example/pages/switch.vue, packages/switch/src/switch.vue
=> Switch: Add change event

example/pages/button.vue, packages/button/src/button.vue
=> Button: fix disabled, fixed #366

example/pages/button.vue, packages/button/src/button.vue
=> (1.x)Button: fix disabled, fixed #366

package.json
=> (1.x)MessageBox: add input type

build/config.js
=> Fix config

packages/button/src/button.vue
=> Button: add click event

packages/search/src/search.vue
=> Search: track-by => key, fixed #380

packages/index-list/src/index-list.vue, packages/index-section/src/index-section.vue
=> IndexList: fix style

packages/loadmore/src/loadmore.vue
=> Loadmore: fix a scrollTop issue

packages/indicator/index.js
=> Indicator: fix a closing bug

build/config.js, packages/indicator/index.js
=> (1.x)Indicator: fix a closing bug

packages/message-box/src/message-box.js, packages/message-box/src/message-box.vue
=> MessageBox: 'message' prop supports HTML template

example/pages/search.vue, packages/search/src/search.vue
=> Search: add autofocus, closed #393

package.json
=> (1.x)MessageBox: 'message' supports HTML template

packages/search/src/search.vue
=> Search: support dynamically modify value, fixed #386

packages/datetime-picker/src/datetime-picker.vue
=> (1.x)DatetimePicker: fix a value sync issue

packages/field/src/field.vue
fix a spelling bug in Field , causes the value cannot  be cleared
=> (1.x)Field: fix a clear content bug

CHANGELOG.md, packages/range/src/index.vue
=> Range: add change event

packages/checklist/src/checklist.vue, packages/field/src/field.vue, packages/radio/src/radio.vue
=> Field/Checklist/Radio: add change event

packages/cell-swipe/src/cell-swipe.vue, packages/cell/src/cell.vue, packages/search/src/search.vue, packages/tab-item/src/tab-item.vue
=> Cell: fix link style, fixed #439

packages/tab-container/src/tab-container.vue
=> TabContainer bug on ios8.x issue #479

packages/actionsheet/src/actionsheet.vue
=> ActionSheet: add stopPropagation on click handler

example/pages/pull-down.vue, example/pages/pull-up.vue, packages/loadmore/src/loadmore.vue
=> Loadmore: remove id

packages/picker/src/picker-slot.vue, packages/picker/src/picker.vue
=> Picker: improve value key

packages/cell-swipe/src/cell-swipe.vue
=> CellSwipe: stop button clicks' propagation, fixed #498

example/pages/swipe.vue, packages/swipe/src/swipe.vue
issues: can set init index when use swipe to present images#474
设置swipe初始的默认页
=> 增加swipe组件defaultIndex属性，用于设置默认页

packages/picker/src/picker-slot.vue, packages/picker/src/picker.vue
=> Picker: fix getSlot bug when toolbar is shown

packages/indicator/index.js
=> Indicator: remove redundant timer

packages/switch/src/switch.vue
when the parent component data change, the ui switch can not be checked. The element  checkbox is ok. so fix it.
=> fix switch

packages/swipe/src/swipe.vue
为 swiper 组件添加 change 事件, 参数是 newIndex.
=> 为 swiper 组件添加一个change事件, issue #523

packages/actionsheet/src/actionsheet.vue, packages/button/src/button.vue, packages/cell-swipe/src/cell-swipe.vue, packages/cell/src/cell.vue, packages/checklist/src/checklist.vue, packages/datetime-picker/src/datetime-picker.vue, packages/field/src/field.vue, packages/indicator/src/indicator.vue, packages/infinite-scroll/src/directive.js, packages/infinite-scroll/src/infinite-scroll.js, packages/message-box/src/message-box.vue, packages/picker/src/draggable.js, packages/picker/src/picker-slot.vue, packages/picker/src/translate.js, packages/popup/src/popup.vue, packages/radio/src/radio.vue, packages/range/src/draggable.js, packages/search/src/search.vue, packages/spinner/src/spinner/fading-circle.vue, packages/swipe/src/swipe.vue, packages/tab-container/src/tab-container.vue, src/index.js, src/utils/dom.js, src/utils/merge.js, src/utils/popup/index.js, src/utils/popup/popup-manager.js
add ssr support
[add ssr more](https://github.com/ElemeFE/mint-ui/issues/548)
=> add ssr support

build/bin/build-entry.js, build/config.js, build/cooking.common.js, package.json, packages/actionsheet/src/actionsheet.vue, packages/button/src/button.vue, packages/cell-swipe/src/cell-swipe.vue, packages/cell/src/cell.vue, packages/checklist/src/checklist.vue, packages/datetime-picker/src/datetime-picker.vue, packages/field/src/field.vue, packages/indicator/src/indicator.vue, packages/message-box/src/message-box.vue, packages/popup/src/popup.vue, packages/radio/src/radio.vue, packages/search/src/search.vue, src/index.js, src/style/popup.css, yarn.lock
=> Fix commonjs build

example/entry.js, yarn.lock
新版 webpack 居然不兼容 commonjs 和 ES6 module 了？略蛋疼
=> Fix import mint, fixed #567

packages/swipe/src/swipe.vue
=> Clear timer when continuous is false && is the last slide, fixed: #585

packages/index-list/src/index-list.vue
index-list组件父元素pading、margin不确定，直接document.body.clientWidth - 10 存在问题。
=> index-list组件BugFix

packages/cell-swipe/src/cell-swipe.vue, packages/swipe/src/swipe.vue
=> Reset offsetLeft after the swipeLeave action

packages/switch/src/switch.vue
Just followed: https://github.com/ftlabs/fastclick/issues/60
=> make switch component works in fastclick

packages/palette-button/src/palette-button.vue, packages/switch/src/switch.vue
- Correct event name in different browsers
- Rounded position number to two decimals, fixed #531
=> Fixed some issues in Palette Button

package.json
=> script: fallback npm

packages/tab-container/src/tab-container.vue
=> Prevent startDrag event when swipeable is false

packages/picker/src/translate.js
os Verision: macOS 10.12.4 Beta (16E144f)/iOS10.3
safari: 10.1 (12603.1.20.1)
=> Safari最新版，element.style 返回的是小写

packages/datetime-picker/src/datetime-picker.vue
=> fixed issue with template in time picker

packages/datetime-picker/src/datetime-picker.vue, packages/picker/src/picker.vue
when you init the picker component the `created` function will set defaultIndex but will not trigger slotValueChange event
=> When set defaultIndex, the defaultValue is wrong

packages/picker/src/picker-slot.vue
=> fix(picker click): If non-touchmove is triggered, will not set translate value in touchend

packages/swipe/src/swipe.vue
添加Swipe组件 切换区块前监听事件为 @before参数为切换前index。 切换动画后为 @end 参数为切换后index。
issues: https://github.com/ElemeFE/mint-ui/issues/615
=> RP Swipe callBack

packages/message-box/src/message-box.js
=> fix(MessageBox close): do nothing when no instance is available

src/utils/popup/index.js
- migrate build env to webpack2
- fix the issue in vue-popup from vue@2.2.1
- use `export` in entry instead of `module.exports`
=> fixed issue with vue@2.2.1

.gitignore, example/pages/picker.vue, packages/picker/src/picker-slot.vue, packages/picker/src/picker.vue
#670 两项小改动:
1. 增加的对picker组件`slot`数组参数中`defaultIndex`属性的变化监听，以便动态地更改picker的默认选项；
2. `.gitignore`文件中添加了对`.vscode`文件夹的忽略项;
=> 监听picker组件defaultIndex参数变化

packages/swipe/src/swipe.vue
=> Add option stopPropagation for swipe

packages/cell/src/cell.vue
=> fix(shadow in android): add position relative to cell-wrapper

packages/infinite-scroll/src/directive.js
=> fixed: infinite-scroll cannot be used with v-if

packages/radio/src/radio.vue
=> fix(radio dot): add border-box to .mint-radio-core

packages/search/src/search.vue
=> remove fake placeholder of Search

packages/field/src/field.vue
=> Change position to relative in .mint-field-other

packages/cell-swipe/src/cell-swipe.vue, packages/cell/src/cell.vue
=> remove relative from .cell-wrapper, add to .cell-swipe-wrapper

packages/picker/src/picker-slot.vue
=> Exchange animationFrameId and cancelAnimationFrame

packages/swipe/src/swipe.vue
=> Fixed timer will not reset if user swipe manually

packages/datetime-picker/src/datetime-picker.vue
=> add datetime-picker cancel event

.gitignore, example/pages/pull-down.vue, packages/loadmore/README.md, packages/loadmore/src/loadmore.vue
add translate changed method to loadmore component
为loadmore组件增加一个translate改变的事件tanslate-change, 通过这个事件可以获取下拉/上拉时候组件的移动距离,从而做一些交互上的改变,例如下拉时候缩放背景图片.
=> add translate changed method to loadmore component

build/bin/build-entry.js, src/index.js
=> fix(lazyload): refix #804

packages/swipe/src/swipe.vue
=> fix(swipe timer): add limitation to initTimer

packages/loadmore/README.md
=> doc(useless api): remove useless api in doc

example/index.tpl
=> feat(example): use the latest vue & vue-router in example

build/bin/build-entry.js
=> fix: … will transform to Object.assign by buble

package.json, src/index.js, yarn.lock
Fixed: #853 
@Leopoldthecoder @QingWei-Li 有坑么？
=> fix: breaking changes from vue@2.3.0

packages/index-list/src/index-list.vue
=> fix: #880 alter indexList’s height when the incoming prop “height” is changed

packages/swipe/src/swipe.vue
=> fix: #844 Swipe组件点击非滑动，触发多次initTimer而未清除Timer造成的Bug

packages/switch/src/switch.vue
=> add disabled

packages/picker/src/picker.vue
=> fix: unnecessary code cause vue@2.4.2 warn(#1000)

packages/tab-container/src/tab-container.vue
=> fix: tab-container component swipe bug on PC

packages/swipe/src/swipe.vue
=> Swipe: smooth swipe gesture

example/pages/pull-down.vue
=>  修复pull-down-demo中的溢出问题#1131

packages/index-list/src/index-list.vue, packages/picker/src/picker-slot.vue
=> picker增加点击选择 + 修复index-list在pc上无法正常显示问题~

packages/cell/src/cell.vue
=> fix: #1165

example/pages/cell-swipe.vue, packages/cell-swipe/src/cell-swipe.vue
=> cell-swipe-fix 增加swipeLock #1128

packages/picker/src/picker-slot.vue, packages/picker/src/picker.vue
=> fix: picker change params

packages/cell-swipe/src/cell-swipe.vue
=> fix(cell-swipe): Stop the click event bubble

example/pages/datetime-picker.vue, packages/datetime-picker/src/datetime-picker.vue
=> feat(datetime-picker): add visible-change and closeOnClickModal
